name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Use subosito/flutter-action@v2 for Flutter setup
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '' # Use stable channe

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/goharshahiapp/"


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
